spring:
  rabbitmq:
    host: 10.0.26.212
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        max-concurrency: 3